name: Minecraft_ScreenShare
version: 1.6.5
author: MPoint
main: net.mpoisv.screen.ScreenShare

api-version: 1.13

commands:
  GetDesktop:
    description: Image Set
    usage: '/<command>'
    permission: 'screen.share.*'